[package]
name = "cotengra"
version = "0.2.0"
authors = ["Johnnie Gray <johnniemcgray@gmail.com>"]
edition = "2024"

[lib]
name = "cotengrust"
crate-type = ["lib", "cdylib"]
path = "src/lib.rs"

[dependencies]
bit-set = "0.8"
num-traits = "0.2"
ordered-float = "5.1"
rand = "0.9"
rustc-hash = "2.1"
wolfram-library-link = { git = "https://github.com/sw1sh/wolfram-library-link-rs", rev = "a266644362d0ad3df2ab4221750b6b7d8c5804ac" }
