[workspace]
members = [
    "TensorNetworks/Cotengra/",
]
resolver = "2"

[patch.crates-io]
wolfram-app-discovery = { git = "https://github.com/sw1sh/wolfram-app-discovery-rs", branch = "bugfix/wstp_discovery" }
wolfram-expr = { git = "https://github.com/sw1sh/wolfram-expr-rs", branch = "feat/wxf-codec-and-integrations", features = ["serde"] }

[profile.release]
opt-level = 3