(* Tests/external_parity/Helpers/ParityHelpers.wl

Helpers for the external-parity test suite. Loads the paclet, provides
capability-gating + skip-recording so that the master runner can distinguish:

  Pass         — assertion held
  Failure      — assertion violated (numeric mismatch or wrong value)
  SkipRNG      — test depends on RNG that cannot be reproduced cross-language
  SkipMissing  — paclet lacks a required symbol/feature for this test
  Error        — test threw an unexpected exception (bug, not gap)

Skipped/missing/error records are kept in global associations so that
run_external_parity.wl can pull them out and write SKIPPED_AND_MISSING.md.
*)

(* Locate worktree root by walking up from cwd looking for PacletInfo.wl. *)
$ParityWorktreeRoot = SelectFirst[
    NestList[ParentDirectory, Directory[], 8],
    DirectoryQ[#] && FileExistsQ[FileNameJoin[{#, "TensorNetworks", "PacletInfo.wl"}]] &,
    Directory[]
];

PacletDirectoryLoad[FileNameJoin[{$ParityWorktreeRoot, "TensorNetworks"}]];
Needs["Wolfram`TensorNetworks`"];
Needs["Wolfram`TensorNetworks`IndexArray`"];
Quiet @ Needs["Wolfram`TensorNetworks`Symmetry`"];

(* Global accumulators — read by the master runner *)
$ParityRNGSkipped = <||>;       (* id -> <| reason, source |> *)
$ParityMissingSkipped = <||>;   (* id -> <| missing -> {syms}, source |> *)
$ParityErrors = <||>;           (* id -> <| error, source |> *)
$ParityCapabilityCache = <||>;  (* sym -> Bool *)

(* Reset all accumulators (called at the start of each tier file) *)
ClearParityRecords[] := (
    $ParityRNGSkipped = <||>;
    $ParityMissingSkipped = <||>;
    $ParityErrors = <||>;
);

(* Capability detection — uses Names[] which handles backticked context strings cleanly. *)
HasSymbolQ[name_String] := Module[{cached},
    cached = Lookup[$ParityCapabilityCache, name, Missing[]];
    If[!MissingQ[cached], Return[cached]];
    cached = Or[
        Names["Wolfram`TensorNetworks`" <> name] =!= {},
        Names["Wolfram`TensorNetworks`IndexArray`" <> name] =!= {},
        Names["Wolfram`TensorNetworks`Symmetry`" <> name] =!= {}
    ];
    AssociateTo[$ParityCapabilityCache, name -> cached];
    cached
];

(* Record a skip due to RNG-dependence *)
RecordSkipRNG[id_String, reason_String, source_String] := (
    AssociateTo[$ParityRNGSkipped, id -> <|"reason" -> reason, "source" -> source|>];
);

(* Record a skip due to missing paclet feature *)
RecordSkipMissing[id_String, missing_List, source_String] := (
    AssociateTo[$ParityMissingSkipped, id -> <|"missing" -> missing, "source" -> source|>];
);

(* Record an error (unexpected exception during test setup or assertion) *)
RecordError[id_String, errMsg_, source_String] := (
    AssociateTo[$ParityErrors, id -> <|"error" -> ToString[errMsg], "source" -> source|>];
);

(* withCapability[{symA, symB, ...}, id, source, body]:
     If all symbols bound, evaluate body. Otherwise record SkipMissing and skip. *)
SetAttributes[WithCapability, HoldRest];
WithCapability[required_List, id_String, source_String, body_] := Module[{missing},
    missing = Select[required, !HasSymbolQ[#] &];
    If[Length[missing] > 0,
        RecordSkipMissing[id, missing, source];
        Null
    ,
        body
    ]
];

(* SkipDueToRNG[id, reason, source] — explicit skip for RNG cases *)
SkipDueToRNG[id_String, reason_String, source_String] := (
    RecordSkipRNG[id, reason, source];
    Null
);

(* parityClose[a, b, tol] — within tol; works for numeric + arrays *)
ParityClose[a_, b_, tol_:1.*^-10] := Module[{diff},
    Catch[
        If[ListQ[a] || ListQ[b],
            If[Dimensions[a] =!= Dimensions[b], Throw[False]];
            Throw[Max[Abs[Flatten[a - b]]] <= tol]
        ];
        Throw[Abs[a - b] <= tol]
    ]
];

(* parityCloseRel[a, b, rtol] — relative tolerance comparison *)
ParityCloseRel[a_, b_, rtol_:1.*^-6] := Module[{denom},
    Catch[
        If[ListQ[a] || ListQ[b],
            If[Dimensions[a] =!= Dimensions[b], Throw[False]];
            denom = Max[Abs[Flatten[b]], 1.*^-30];
            Throw[Max[Abs[Flatten[a - b]]] / denom <= rtol]
        ];
        denom = Max[Abs[b], 1.*^-30];
        Throw[Abs[a - b] / denom <= rtol]
    ]
];

(* ParityWriteSkipLog[outFile] — called by the master runner. *)
ParityWriteSkipLog[outFile_String,
    Optional[passCount_Integer, 0],
    Optional[failCount_Integer, 0]] := Module[{lines, time, sec},
    time = DateString[];
    lines = {};
    AppendTo[lines, "# Skipped & Missing Features Report"];
    AppendTo[lines, ""];
    AppendTo[lines, "Auto-generated by `run_external_parity.wl` on " <> time <> "."];
    AppendTo[lines, ""];
    AppendTo[lines, "## Summary"];
    AppendTo[lines, ""];
    AppendTo[lines, "- Passed: " <> ToString[passCount]];
    AppendTo[lines, "- Failed: " <> ToString[failCount]];
    AppendTo[lines, "- Skipped (RNG-dependent): " <> ToString[Length[$ParityRNGSkipped]]];
    AppendTo[lines, "- Skipped (paclet feature missing): " <> ToString[Length[$ParityMissingSkipped]]];
    AppendTo[lines, "- Errors (unexpected): " <> ToString[Length[$ParityErrors]]];
    AppendTo[lines, ""];

    mkRow[cells_] := "| " <> StringRiffle[Map[ToString, cells], " | "] <> " |";

    sec[title_, items_, headerCols_, rowFn_] := (
        AppendTo[lines, "## " <> title];
        AppendTo[lines, ""];
        If[Length[items] === 0,
            AppendTo[lines, "_(none)_"];
        ,
            AppendTo[lines, mkRow[headerCols]];
            AppendTo[lines, mkRow[ConstantArray["---", Length[headerCols]]]];
            KeyValueMap[
                Function[{id, info}, AppendTo[lines, mkRow[rowFn[id, info]]]],
                items
            ];
        ];
        AppendTo[lines, ""];
    );

    sec["Skipped: RNG-dependent",
        $ParityRNGSkipped,
        {"Test ID", "Source", "Reason"},
        Function[{id, info},
            {id, Lookup[info, "source", ""], Lookup[info, "reason", ""]}]];

    sec["Skipped: paclet feature missing",
        $ParityMissingSkipped,
        {"Test ID", "Source", "Missing symbols"},
        Function[{id, info},
            {id, Lookup[info, "source", ""],
             StringRiffle[Map[ToString, Lookup[info, "missing", {}]], ", "]}]];

    sec["Errors (unexpected -- investigate as bugs)",
        $ParityErrors,
        {"Test ID", "Source", "Error"},
        Function[{id, info},
            {id, Lookup[info, "source", ""], Lookup[info, "error", ""]}]];

    Export[outFile, StringRiffle[lines, "\n"], "Text"];
    outFile
];
