(* Autogenerate TensorNetworks example notebook (excludes IndexArray functions) *)
SetDirectory[NotebookDirectory[] /. $Failed -> "/Users/mohammadb/Documents/GitHub/TensorNetworks/Documentation"];
Needs["Wolfram`TensorNetworks`"];

commonSetup = "Needs[\"Wolfram`TensorNetworks`\"];\nSeedRandom[1];\nA = RandomReal[1, {2, 3}];\nB = RandomReal[1, {3, 4}];\nC = RandomReal[1, {4, 2}];\nD = RandomReal[1, {2, 2}];\nE = RandomComplex[{-1 - I, 1 + I}, {2, 2}];\nindices = {{i, j}, {j, k}, {k, i}};\ntn = TensorNetwork[{A, B, C}, indices];\ng = ToTensorNetworkGraph[tn];\ndata = TensorNetworkData[tn];\npath = OptimalContractionPath[tn];\ntreePath = PathToTreePath[path, data[\"Vertices\"]];\nmps = RandomTensorNetwork[\"MPS\"[5, 3, 2]];\nmps2 = RandomTensorNetwork[\"MPS\"[5, 3, 2], \"Boundary\" -> \"Periodic\"];\nsizeDict = <|i -> 2, j -> 3, k -> 4, l -> 2, m -> 2, n -> 3|>;\nyt1 = YoungTableau[{{1, 2}, {3}}];\nyt2 = YoungTableau[{2, 1}];\nt3 = RandomReal[1, {2, 2, 2}];\ncyc = ToTensorNetworkGraph[{A, B, C}, {{1, 2}, {2, 3}, {3, 1}}];";

examples = <|
"EinsteinSummation" -> {
"EinsteinSummation[{{i, j}, {j, k}} -> {i, k}, {A, B}]",
"EinsteinSummation[{{i, j}, {j, k}}, {A, B}]",
"EinsteinSummation[\"ij,jk->ik\", {A, B}]",
"EinsteinSummation[\"ij,jk\", {A, B}]",
"EinsteinSummation[{{i, j, j}, {j, k}}, {A, B}]",
"EinsteinSummation[{ {i, j}, {j, k}, {k, i} } -> { }, {A, B, C}]",
"EinsteinSummation[{{}, {}}, {1.2, 3.4}]",
"EinsteinSummation[{{i}, {i}}, {A[[All, 1]], A[[All, 2]]}]",
"EinsteinSummation[{{i, j}, {j, k}}, {SparseArray[A], B}]",
"EinsteinSummation[{Characters /@ {\"ij\", \"jk\"}} -> Characters[\"ik\"], {A, B}]"
},
"IndexedMultiply" -> {
"IndexedMultiply[{{i, j}, {j, k}}, {A, B}]",
"IndexedMultiply[{{i}, {i}}, {A[[All, 1]], A[[All, 2]]}]",
"IndexedMultiply[{{i, j, k}, {i, j, k}}, {RandomReal[1, {2, 3, 4}], RandomReal[1, {2, 3, 4}]}]",
"IndexedMultiply[{{i, j}, {i, j}}, {SparseArray[A], SparseArray[A]}]",
"IndexedMultiply[{{i, j}, {j, k}, {k, l}}, {A, B, RandomReal[1, {4, 5}]}]",
"IndexedMultiply[{{}, {}}, {3., 5.}]",
"IndexedMultiply[{{i, j}, {j, i}}, {A, Transpose[A]}]",
"IndexedMultiply[{{i, i}, {i, i}}, {DiagonalMatrix[{1, 2}], DiagonalMatrix[{3, 4}]}]",
"IndexedMultiply[{{i, j}, {j, k}}, {ArraySymbol[\"T\", {2, 3}], ArraySymbol[\"S\", {3, 4}]}]",
"IndexedMultiply[{{i}, {j}}, {Range[5], Range[6]}]"
},
"ActivateTensors" -> {
"exprInactive = TensorNetworkContraction[tn, path, \"Inactive\" -> True];",
"ActivateTensors[exprInactive]",
"ActivateTensors[Inactive[TensorContract][Inactive[TensorProduct][A, B], {{2, 3}}]]",
"ActivateTensors[Inactive[Transpose][Inactive[TensorContract][Inactive[TensorProduct][A, B], {{2, 3}}], Cycles[{{1, 2}}]]]",
"ActivateTensors[Inactive[TensorProduct][SymbolicDeltaProductArray[{2, 2}, {{1, 2}}], A]]",
"ActivateTensors[Inactive[TensorContract][t3, {{1, 2}}]]",
"ActivateTensors[Inactive[TensorProduct][A, B, C]]",
"ActivateTensors[Inactive[TensorContract][Inactive[TensorProduct][A, B, C], {{2, 3}, {4, 5}}]]",
"ActivateTensors[Inactive[GeneralizedPower][TensorProduct, A, 2]]",
"ActivateTensors[exprInactive /. Inactive[TensorContract][x_, y_] :> Inactive[TensorContract][x, y]]"
},
"TensorNetwork" -> {
"TensorNetwork[{A, B}, {{1, 2}, {2, 3}}]",
"TensorNetwork[{A, B}, {{i, j}, {j, k}} -> {i, k}]",
"TensorNetwork[{A, B}, {{i, j}, {j, k}}, Cycles[{{1, 2}}]]",
"TensorNetwork[TensorContract[TensorProduct[A, B], {{2, 3}}]]",
"TensorNetwork[Transpose[TensorContract[TensorProduct[A, B], {{2, 3}}], Cycles[{{1, 2}}]]]",
"TensorNetwork[g]",
"TensorNetwork[{{1, 2}, {2, 3}}]",
"TensorNetwork[{{1, 2}, {2, 3}} -> {1, 3}]",
"TensorNetwork[{A, B, C}, indices]",
"TensorNetwork[{ArraySymbol[\"X\", {2, 2}], ArraySymbol[\"Y\", {2, 2}]}, {{1, 2}, {2, 3}}]"
},
"TensorNetworkQ" -> {
"TensorNetworkQ[tn]",
"TensorNetworkQ[TensorNetwork[{A}, {{1, 1}}]]",
"TensorNetworkQ[TensorNetwork[{A}, {{1, 2}}]]",
"TensorNetworkQ[\"not a network\"]",
"TensorNetworkQ[TensorNetwork[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkQ[TensorNetwork[{A, B}, {{1, 2}, {2, 2}}]]",
"TensorNetworkQ[TensorNetwork[{A, B}, {{1, 2}, {2, 3}}, Cycles[{{1, 2}}]]]",
"TensorNetworkQ[TensorNetwork[{A, B}, {{1, 2}, {2, 3}}, Automatic]]",
"TensorNetworkQ[TensorNetworkAdd[tn, D, {m, n}]]",
"TensorNetworkQ[TensorNetworkDelete[tn, -1]]"
},
"TensorNetworkData" -> {
"TensorNetworkData[tn]",
"TensorNetworkData[BinaryTensorNetwork[tn]]",
"TensorNetworkData[SparseTensorNetwork[tn]]",
"TensorNetworkData[TensorNetworkAdd[tn, D, {m, n}]]",
"TensorNetworkData[TensorNetworkDelete[tn, -1]]",
"TensorNetworkData[RandomTensorNetwork[{4, 4}, 3]]",
"TensorNetworkData[TensorNetwork[{A, B}, {{i, j}, {j, i}}]]",
"TensorNetworkData[TensorNetwork[{A}, {{}}]]",
"TensorNetworkData[TensorNetwork[{A, B}, {{1, 2}, {2, 1}}]]",
"TensorNetworkData[TensorNetwork[{ArraySymbol[\"X\", {2, 2}], ArraySymbol[\"Y\", {2, 2}]}, {{1, 2}, {2, 3}}]]"
},
"TensorNetworkSize" -> {
"TensorNetworkSize[tn]",
"TensorNetworkSize[BinaryTensorNetwork[tn]]",
"TensorNetworkSize[SparseTensorNetwork[tn]]",
"TensorNetworkSize[TensorNetworkAdd[tn, D, {m, n}]]",
"TensorNetworkSize[TensorNetworkDelete[tn, -1]]",
"TensorNetworkSize[RandomTensorNetwork[{5, 6}, 3]]",
"TensorNetworkSize[TensorNetwork[{A}, {{}}]]",
"TensorNetworkSize[TensorNetwork[{A, B}, {{1, 2}, {2, 1}}]]",
"TensorNetworkSize[TensorNetwork[{A, B, C}, indices]]",
"TensorNetworkSize[TensorNetwork[{ArraySymbol[\"X\", {2, 2}]}, {{1, 2}}]]"
},
"TensorNetworkContractions" -> {
"TensorNetworkContractions[tn]",
"TensorNetworkContractions[BinaryTensorNetwork[tn]]",
"TensorNetworkContractions[TensorNetworkAdd[tn, D, {m, n}]]",
"TensorNetworkContractions[TensorNetworkDelete[tn, -1]]",
"TensorNetworkContractions[TensorNetwork[{A, B}, {{i, j}, {j, i}}]]",
"TensorNetworkContractions[TensorNetwork[{A}, {{}}]]",
"TensorNetworkContractions[TensorNetwork[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkContractions[TensorNetwork[{A, B, C}, indices]]",
"TensorNetworkContractions[TensorNetwork[{ArraySymbol[\"X\", {2, 2}], ArraySymbol[\"Y\", {2, 2}]}, {{1, 2}, {2, 3}}]]",
"TensorNetworkContractions[TensorNetwork[{A, B}, {{1, 1}, {1, 1}}]]"
},
"RandomTensorNetwork" -> {
"RandomTensorNetwork[{6, 8}, 4]",
"RandomTensorNetwork[{6, 8}, {3}]",
"RandomTensorNetwork[{6, 8}, 4, 1]",
"RandomTensorNetwork[{6, 8}, {3}, 2, Method -> \"Complex\"]",
"RandomTensorNetwork[RandomGraph[{6, 8}], 4]",
"RandomTensorNetwork[RandomGraph[{6, 8}], {3}, 1, Method -> \"Complex\"]",
"RandomTensorNetwork[\"MPS\"[6, 3, 2]]",
"RandomTensorNetwork[\"MPS\"[6, 3, 2], \"Boundary\" -> \"Periodic\"]",
"RandomTensorNetwork[\"TT\"[6, 3]]",
"RandomTensorNetwork[\"MPO\"[4, 2, 2]]"
},
"TensorNetworkAdd" -> {
"TensorNetworkAdd[tn, D, {m, n}]",
"TensorNetworkAdd[tn, RandomReal[1, {2, 2, 2}], {m, n, k}]",
"TensorNetworkAdd[tn, RandomComplex[{-1 - I, 1 + I}, {2, 2}], {i, j}]",
"TensorNetworkAdd[TensorNetworkDelete[tn, -1], C, {k, i}]",
"TensorNetworkAdd[TensorNetwork[{A}, {{i, j}}], B, {j, k}]",
"TensorNetworkAdd[TensorNetwork[{A, B}, {{1, 2}, {2, 3}}], C, {3, 1}]",
"TensorNetworkAdd[tn, ArraySymbol[\"New\", {2, 2}], {p, q}]",
"TensorNetworkAdd[tn, RandomReal[1, {3}], {i}]",
"TensorNetworkAdd[tn, RandomReal[1, {2, 2}], {i, i}]",
"TensorNetworkAdd[TensorNetwork[{A}, {{}}], 7., {}]"
},
"TensorNetworkDelete" -> {
"TensorNetworkDelete[tn, -1]",
"TensorNetworkDelete[tn, 1]",
"TensorNetworkDelete[TensorNetworkAdd[tn, D, {m, n}], 4]",
"TensorNetworkDelete[TensorNetwork[{A, B}, {{i, j}, {j, k}}], 2]",
"TensorNetworkDelete[TensorNetwork[{A, B, C}, indices], 2]",
"TensorNetworkDelete[TensorNetwork[{A, B, C}, indices], 3]",
"TensorNetworkDelete[TensorNetworkAdd[tn, RandomReal[1, {2, 2}], {m, n}], -1]",
"TensorNetworkDelete[TensorNetwork[{A}, {{}}], 1]",
"TensorNetworkDelete[TensorNetwork[{A, B}, {{1, 2}, {2, 3}}], 1]",
"TensorNetworkDelete[TensorNetwork[{A, B, C}, {{1, 2}, {2, 3}, {3, 1}}], 2]"
},
"BinaryTensorNetwork" -> {
"BinaryTensorNetwork[tn]",
"BinaryTensorNetwork[TensorNetwork[{A, B}, {{i, j}, {j, i}}]]",
"BinaryTensorNetwork[RandomTensorNetwork[{5, 5}, 3]]",
"BinaryTensorNetwork[TensorNetwork[{A, B, C}, indices]]",
"BinaryTensorNetwork[SparseTensorNetwork[tn]]",
"BinaryTensorNetwork[TensorNetworkAdd[tn, D, {m, n}]]",
"BinaryTensorNetwork[TensorNetwork[{A, B}, {{1, 2}, {2, 3}}]]",
"BinaryTensorNetwork[TensorNetwork[{A}, {{}}]]",
"BinaryTensorNetwork[TensorNetwork[{A, B}, {{1, 2}, {2, 1}}]]",
"BinaryTensorNetwork[TensorNetwork[{A, B, C}, {{1, 2}, {2, 3}, {3, 4}}]]"
},
"BinaryTensorNetworkQ" -> {
"BinaryTensorNetworkQ[tn]",
"BinaryTensorNetworkQ[BinaryTensorNetwork[tn]]",
"BinaryTensorNetworkQ[TensorNetwork[{A, B}, {{i, j}, {j, i}}]]",
"BinaryTensorNetworkQ[TensorNetwork[{A, B, C}, indices]]",
"BinaryTensorNetworkQ[SparseTensorNetwork[tn]]",
"BinaryTensorNetworkQ[TensorNetworkAdd[tn, D, {m, n}]]",
"BinaryTensorNetworkQ[TensorNetwork[{A}, {{}}]]",
"BinaryTensorNetworkQ[TensorNetwork[{A, B}, {{1, 2}, {2, 3}}]]",
"BinaryTensorNetworkQ[TensorNetwork[{A, B, C}, {{1, 2}, {2, 3}, {3, 2}}]]",
"BinaryTensorNetworkQ[TensorNetwork[{A, B, C}, {{1, 2}, {2, 3}, {3, 4}}]]"
},
"SparseTensorNetwork" -> {
"SparseTensorNetwork[tn]",
"SparseTensorNetwork[TensorNetwork[{A, B}, {{i, j}, {j, k}}]]",
"SparseTensorNetwork[TensorNetwork[{A, B, C}, indices]]",
"SparseTensorNetwork[BinaryTensorNetwork[tn]]",
"SparseTensorNetwork[TensorNetworkAdd[tn, D, {m, n}]]",
"SparseTensorNetwork[TensorNetwork[{SparseArray[A]}, {{1, 2}}]]",
"SparseTensorNetwork[TensorNetwork[{A}, {{}}]]",
"SparseTensorNetwork[TensorNetwork[{A, B}, {{1, 2}, {2, 3}}]]",
"SparseTensorNetwork[RandomTensorNetwork[{4, 4}, 3]]",
"SparseTensorNetwork[RandomTensorNetwork[\"MPO\"[3, 2, 2]]]"
},
"TensorNetworkGraphQ" -> {
"TensorNetworkGraphQ[g]",
"TensorNetworkGraphQ[g, True]",
"TensorNetworkGraphQ[True][g]",
"TensorNetworkGraphQ[RandomGraph[{3, 2}], True]",
"TensorNetworkGraphQ[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkGraphQ[ToTensorNetworkGraph[{A}, {{}}]]",
"TensorNetworkGraphQ[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 1}}]]",
"TensorNetworkGraphQ[ToTensorNetworkGraph[{A, B, C}, indices]]",
"TensorNetworkGraphQ[TensorNetworkRemoveCycles[cyc]]",
"TensorNetworkGraphQ[Graph[{1 -> 2, 2 -> 1}]]"
},
"TensorNetworkIndexGraph" -> {
"TensorNetworkIndexGraph[g]",
"TensorNetworkIndexGraph[g, VertexLabels -> Automatic]",
"TensorNetworkIndexGraph[g, EdgeLabels -> Automatic]",
"TensorNetworkIndexGraph[BinaryTensorNetwork[tn][\"Graph\"]]",
"TensorNetworkIndexGraph[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkIndexGraph[ToTensorNetworkGraph[{A}, {{}}]]",
"TensorNetworkIndexGraph[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 1}}], ImageSize -> Small]",
"TensorNetworkIndexGraph[TensorNetworkRemoveCycles[cyc]]",
"TensorNetworkIndexGraph[ToTensorNetworkGraph[RandomTensorNetwork[{4, 4}, 3]]]",
"TensorNetworkIndexGraph[ToTensorNetworkGraph[RandomTensorNetwork[\"TT\"[5, 2]]]]"
},
"ToTensorNetworkGraph" -> {
"ToTensorNetworkGraph[tn]",
"ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}]",
"ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}, Method -> \"Symbolic\"]",
"ToTensorNetworkGraph[DirectedGraph[{1 -> 2, 2 -> 3}], Method -> \"Symbolic\"]",
"ToTensorNetworkGraph[Graph[{1 <-> 2, 2 <-> 3}], Method -> \"Random\", VertexLabels -> \"Name\"]",
"ToTensorNetworkGraph[DirectedGraph[{1 -> 2}], Method -> \"Zero\"]",
"ToTensorNetworkGraph[DirectedGraph[{1 -> 2}], Method -> \"RandomComplex\"]",
"ToTensorNetworkGraph[{A, B, C}, indices]",
"ToTensorNetworkGraph[{A}, {{}}]",
"ToTensorNetworkGraph[tn, VertexLabels -> Automatic]"
},
"TensorNetworkIndices" -> {
"TensorNetworkIndices[g]",
"TensorNetworkIndices[tn]",
"TensorNetworkIndices[TensorNetworkRemoveCycles[cyc]]",
"TensorNetworkIndices[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkIndices[ToTensorNetworkGraph[{A}, {{}}]]",
"TensorNetworkIndices[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 1}}]]",
"TensorNetworkIndices[ToTensorNetworkGraph[{A, B, C}, indices]]",
"TensorNetworkIndices[BinaryTensorNetwork[tn][\"Graph\"]]",
"TensorNetworkIndices[TensorNetworkAdd[tn, D, {m, n}][\"Graph\"]]",
"TensorNetworkIndices[TensorNetworkReplaceIndices[g, {Superscript[1, 1] -> Superscript[1, 10]}]]"
},
"TensorNetworkTensors" -> {
"TensorNetworkTensors[g]",
"TensorNetworkTensors[tn]",
"TensorNetworkTensors[TensorNetworkRemoveCycles[cyc]]",
"TensorNetworkTensors[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkTensors[ToTensorNetworkGraph[{A}, {{}}]]",
"TensorNetworkTensors[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 1}}]]",
"TensorNetworkTensors[BinaryTensorNetwork[tn][\"Graph\"]]",
"TensorNetworkTensors[TensorNetworkAdd[tn, D, {m, n}][\"Graph\"]]",
"TensorNetworkTensors[TensorNetworkReplaceIndices[g, {Superscript[1, 1] -> Superscript[1, 10]}]]",
"TensorNetworkTensors[ToTensorNetworkGraph[RandomTensorNetwork[{4, 4}, 3]]]"
},
"TensorNetworkGraphData" -> {
"TensorNetworkGraphData[g]",
"TensorNetworkGraphData[tn]",
"TensorNetworkGraphData[TensorNetworkRemoveCycles[cyc]]",
"TensorNetworkGraphData[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkGraphData[ToTensorNetworkGraph[{A}, {{}}]]",
"TensorNetworkGraphData[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 1}}]]",
"TensorNetworkGraphData[BinaryTensorNetwork[tn][\"Graph\"]]",
"TensorNetworkGraphData[TensorNetworkAdd[tn, D, {m, n}][\"Graph\"]]",
"TensorNetworkGraphData[TensorNetworkReplaceIndices[g, {Superscript[1, 1] -> Superscript[1, 10]}]]",
"TensorNetworkGraphData[ToTensorNetworkGraph[RandomTensorNetwork[{4, 4}, 3]]]"
},
"TensorNetworkIndexDimensions" -> {
"TensorNetworkIndexDimensions[g]",
"TensorNetworkIndexDimensions[TensorNetworkData[tn]]",
"TensorNetworkIndexDimensions[TensorNetworkIndices[g], TensorNetworkTensors[g]]",
"TensorNetworkIndexDimensions[{{i, j}, {j, k}}, {A, B}]",
"TensorNetworkIndexDimensions[tn]",
"TensorNetworkIndexDimensions[BinaryTensorNetwork[tn]]",
"TensorNetworkIndexDimensions[TensorNetworkAdd[tn, D, {m, n}]]",
"TensorNetworkIndexDimensions[TensorNetworkReplaceIndices[g, {Superscript[1, 1] -> Superscript[1, 10]}]]",
"TensorNetworkIndexDimensions[TensorNetworkRemoveCycles[cyc]]",
"TensorNetworkIndexDimensions[ToTensorNetworkGraph[{A}, {{}}]]"
},
"TensorNetworkFreeIndices" -> {
"TensorNetworkFreeIndices[g]",
"TensorNetworkFreeIndices[TensorNetworkIndices[g], EdgeTags[g]]",
"TensorNetworkFreeIndices[{{a, b}, {b, c}, {c}}]",
"TensorNetworkFreeIndices[tn]",
"TensorNetworkFreeIndices[BinaryTensorNetwork[tn]]",
"TensorNetworkFreeIndices[TensorNetworkAdd[tn, D, {m, n}]]",
"TensorNetworkFreeIndices[TensorNetworkDelete[tn, -1]]",
"TensorNetworkFreeIndices[TensorNetworkRemoveCycles[cyc]]",
"TensorNetworkFreeIndices[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkFreeIndices[ToTensorNetworkGraph[{A}, {{}}]]"
},
"TensorNetworkRemoveCycles" -> {
"TensorNetworkRemoveCycles[cyc]",
"TensorNetworkRemoveCycles[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 1}}]]",
"TensorNetworkRemoveCycles[Graph[{1 -> 2, 2 -> 3, 3 -> 1}]]",
"TensorNetworkRemoveCycles[ToTensorNetworkGraph[{A, B, C}, {{1, 2}, {2, 3}, {3, 1}}]]",
"TensorNetworkRemoveCycles[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 1}}], VertexLabels -> Automatic]",
"TensorNetworkRemoveCycles[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkRemoveCycles[ToTensorNetworkGraph[{A}, {{}}]]",
"TensorNetworkRemoveCycles[ToTensorNetworkGraph[RandomTensorNetwork[{4, 4}, 3]]]",
"TensorNetworkRemoveCycles[ToTensorNetworkGraph[RandomTensorNetwork[\"TT\"[5, 2]]]]",
"TensorNetworkRemoveCycles[ToTensorNetworkGraph[RandomTensorNetwork[\"MPO\"[3, 2, 2]]]]"
},
"TensorNetworkToNetGraph" -> {
"TensorNetworkToNetGraph[g]",
"TensorNetworkToNetGraph[g, path]",
"TensorNetworkToNetGraph[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}]]",
"TensorNetworkToNetGraph[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}], {1 -> 2}]",
"TensorNetworkToNetGraph[ToTensorNetworkGraph[{A}, {{}}]]",
"TensorNetworkToNetGraph[ToTensorNetworkGraph[{A, B, C}, indices]]",
"TensorNetworkToNetGraph[TensorNetworkRemoveCycles[cyc]]",
"TensorNetworkToNetGraph[ToTensorNetworkGraph[RandomTensorNetwork[{4, 4}, 3]]]",
"TensorNetworkToNetGraph[ToTensorNetworkGraph[RandomTensorNetwork[\"TT\"[5, 2]]]]",
"TensorNetworkToNetGraph[ToTensorNetworkGraph[RandomTensorNetwork[\"MPO\"[3, 2, 2]]]]"
},
"TensorNetworkReplaceIndices" -> {
"TensorNetworkReplaceIndices[g, {Superscript[1, 1] -> Superscript[1, 10]}]",
"TensorNetworkReplaceIndices[g, {Subscript[2, 1] -> Subscript[2, 5]}]",
"TensorNetworkReplaceIndices[g, {Superscript[1, 1] -> Superscript[1, 1]}]",
"TensorNetworkReplaceIndices[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}], {Superscript[1, 1] -> Superscript[1, 9]}]",
"TensorNetworkReplaceIndices[ToTensorNetworkGraph[{A}, {{}}], {Superscript[1, 1] -> Superscript[1, 2]}]",
"TensorNetworkReplaceIndices[TensorNetworkRemoveCycles[cyc], {Superscript[1, 1] -> Superscript[1, 7]}]",
"TensorNetworkReplaceIndices[ToTensorNetworkGraph[RandomTensorNetwork[{4, 4}, 3]], {Superscript[1, 1] -> Superscript[1, 6]}]",
"TensorNetworkReplaceIndices[ToTensorNetworkGraph[RandomTensorNetwork[\"TT\"[5, 2]]], {Superscript[1, 1] -> Superscript[1, 8]}]",
"TensorNetworkReplaceIndices[ToTensorNetworkGraph[RandomTensorNetwork[\"MPO\"[3, 2, 2]]], {Superscript[1, 1] -> Superscript[1, 4]}]",
"TensorNetworkReplaceIndices[g, {Superscript[1, 1] -> Subscript[1, 1]}]"
},
"InitializeTensorNetwork" -> {
"InitializeTensorNetwork[g, D]",
"InitializeTensorNetwork[g, D, Automatic]",
"InitializeTensorNetwork[g, D, {Superscript[0, 1], Superscript[0, 2]}]",
"InitializeTensorNetwork[ToTensorNetworkGraph[{A, B}, {{1, 2}, {2, 3}}], D]",
"InitializeTensorNetwork[ToTensorNetworkGraph[{A}, {{}}], 5]",
"InitializeTensorNetwork[ToTensorNetworkGraph[{A, B, C}, indices], RandomReal[1, {2, 2}], Automatic]",
"InitializeTensorNetwork[TensorNetworkRemoveCycles[cyc], D]",
"InitializeTensorNetwork[ToTensorNetworkGraph[RandomTensorNetwork[{4, 4}, 3]], D]",
"InitializeTensorNetwork[ToTensorNetworkGraph[RandomTensorNetwork[\"TT\"[5, 2]]], D]",
"InitializeTensorNetwork[ToTensorNetworkGraph[RandomTensorNetwork[\"MPO\"[3, 2, 2]]], D]"
},
"GreedyContractionPath" -> {
"GreedyContractionPath[tn]",
"GreedyContractionPath[g]",
"GreedyContractionPath[data]",
"GreedyContractionPath[{{i, j}, {j, k}, {k, l}}, {i, l}, sizeDict]",
"GreedyContractionPath[{{i, j}, {j, k}}, {i, k}, sizeDict, \"MemoryWeight\" -> 1., \"Temperature\" -> 0.1, \"MaxNeighbors\" -> 20, \"RandomSeed\" -> 123]",
"GreedyContractionPath[{{i, j}, {j, k}}, {i, k}, sizeDict, \"PreSimplify\" -> True, \"FixedIndexing\" -> True]",
"GreedyContractionPath[RandomTensorNetwork[{5, 6}, 3]]",
"GreedyContractionPath[TensorNetwork[{A, B}, {{i, j}, {j, i}}]]",
"GreedyContractionPath[TensorNetwork[{A, B, C}, indices]]",
"GreedyContractionPath[BinaryTensorNetwork[tn]]"
},
"OptimalContractionPath" -> {
"OptimalContractionPath[tn]",
"OptimalContractionPath[g]",
"OptimalContractionPath[data]",
"OptimalContractionPath[{{i, j}, {j, k}, {k, l}}, {i, l}, sizeDict]",
"OptimalContractionPath[{{i, j}, {j, k}}, {i, k}, sizeDict, Method -> \"size\", \"PruningThreshold\" -> 1.]",
"OptimalContractionPath[{{i, j}, {j, k}, {k, i}}, { }, sizeDict, Method -> \"flops\", \"PruningThreshold\" -> 0.5]",
"OptimalContractionPath[RandomTensorNetwork[{5, 6}, 3]]",
"OptimalContractionPath[TensorNetwork[{A, B}, {{i, j}, {j, i}}]]",
"OptimalContractionPath[TensorNetwork[{A, B, C}, indices], Method -> \"flops\"]",
"OptimalContractionPath[BinaryTensorNetwork[tn], Method -> \"size\"]"
},
"$TensorNetworkContractionMethods" -> {
"$TensorNetworkContractionMethods",
"MemberQ[$TensorNetworkContractionMethods, \"ArrayDot\"]",
"Length[$TensorNetworkContractionMethods]",
"$TensorNetworkContractionMethods[[1]]",
"StringJoin[Riffle[$TensorNetworkContractionMethods, \" | \" ]]",
"Select[$TensorNetworkContractionMethods, StringContainsQ[\"Dot\"]]",
"Take[$TensorNetworkContractionMethods, 3]",
"Sort[$TensorNetworkContractionMethods]",
"AssociationThread[$TensorNetworkContractionMethods, Range[Length[$TensorNetworkContractionMethods]]]",
"Replace[$TensorNetworkContractionMethods, {x__} :> {x}]"
},
"TensorNetworkContraction" -> {
"TensorNetworkContraction[tn, path, Method -> \"ArrayDotTranspose\", \"Inactive\" -> True]",
"TensorNetworkContraction[data, treePath, Method -> \"TensorContract\", \"Inactive\" -> True]",
"TensorNetworkContraction[tn, \"Greedy\"]",
"TensorNetworkContraction[tn, \"Optimal\"]",
"TensorNetworkContraction[data, Method -> \"Dot\", \"Inactive\" -> True]",
"TensorNetworkContraction[data, Method -> \"TableSum\", \"Inactive\" -> True]",
"TensorNetworkContraction[tn, path, \"TransposeFunction\" -> Transpose, \"Inactive\" -> True]",
"TensorNetworkContraction[TensorNetwork[{A, B}, {{i, j}, {j, i}}], Method -> \"ArrayDot\", \"Inactive\" -> True]",
"TensorNetworkContraction[TensorNetwork[{A}, {{}}]]",
"TensorNetworkContraction[BinaryTensorNetwork[tn], \"Greedy\"]"
},
"TensorNetworkContract" -> {
"TensorNetworkContract[tn]",
"TensorNetworkContract[tn, path, Method -> \"ArrayDot\"]",
"TensorNetworkContract[data, path, Method -> \"TensorContract\"]",
"TensorNetworkContract[tn, \"Greedy\"]",
"TensorNetworkContract[tn, \"Optimal\"]",
"TensorNetworkContract[TensorNetwork[{A, B}, {{i, j}, {j, i}}]]",
"TensorNetworkContract[TensorNetwork[{A}, {{}}]]",
"TensorNetworkContract[BinaryTensorNetwork[tn], path]",
"TensorNetworkContract[TensorNetwork[{A, B, C}, indices], Method -> \"ArrayDotTranspose\"]",
"TensorNetworkContract[SparseTensorNetwork[tn]]"
},
"ContractionTree" -> {
"ContractionTree[TensorNetworkContraction[tn, path, \"Inactive\" -> True]]",
"ContractionTree[TensorNetworkContraction[tn, \"Greedy\", \"Inactive\" -> True], \"Labels\" -> \"Dimensions\"]",
"ContractionTree[TensorNetworkContraction[tn, \"Greedy\", \"Inactive\" -> True], ImageSize -> Medium]",
"ContractionTree[TensorNetworkContraction[TensorNetwork[{A, B}, {{i, j}, {j, i}}], \"Inactive\" -> True]]",
"ContractionTree[TensorNetworkContraction[TensorNetwork[{A}, {{}}], \"Inactive\" -> True]]",
"ContractionTree[TensorNetworkContraction[BinaryTensorNetwork[tn], \"Inactive\" -> True]]",
"ContractionTree[TensorNetworkContraction[TensorNetwork[{A, B, C}, indices], \"Inactive\" -> True], TreeLayout -> Right]",
"ContractionTree[TensorNetworkContraction[SparseTensorNetwork[tn], \"Inactive\" -> True]]",
"ContractionTree[TensorNetworkContraction[tn, path, \"Inactive\" -> True], TreeElementLabelStyle -> {All -> FontSize -> 6}]",
"ContractionTree[TensorNetworkContraction[tn, path, \"Inactive\" -> True], AspectRatio -> 1/2]"
},
"TreePathQ" -> {
"TreePathQ[{{1}, {2}}]",
"TreePathQ[{}]",
"TreePathQ[{ {1, 2}, {3} }]",
"TreePathQ[{ { {1}, {2} }, { {3} } }]",
"TreePathQ[{{1}}]",
"TreePathQ[{{1}, {2, 3}}]",
"TreePathQ[{{1}, { {2}, {3} }}]",
"TreePathQ[{1, 2}]",
"TreePathQ[\"not a path\"]",
"TreePathQ[TreePathToPath[{{1}, {2}}]]"
},
"PathQ" -> {
"PathQ[{{1, 2}, {1, 2}}]",
"PathQ[{{1}, {2}}]",
"PathQ[{{1, 2}}]",
"PathQ[{{1, 2}, {2, 3}, {1, 3}}]",
"PathQ[{{1, 2, 3}}]",
"PathQ[{}]",
"PathQ[{{1, 2}, {1, 2, 3}}]",
"PathQ[{{1, 2}, {2}}]",
"PathQ[\"invalid\"]",
"PathQ[PathToTreePath[{{1, 2}}]]"
},
"CanonicalPathQ" -> {
"CanonicalPathQ[{{1, 2}, {1, 2}}]",
"CanonicalPathQ[{{1, 2}}]",
"CanonicalPathQ[{{1, 2}, {2, 3}}]",
"CanonicalPathQ[{{1, 2, 3}}]",
"CanonicalPathQ[{}]",
"CanonicalPathQ[{{1, 2}, {1, 3}}]",
"CanonicalPathQ[{{1, 2}, {1, 2, 3}}]",
"CanonicalPathQ[{{1, 2}, {2, 3}, {1, 3}}]",
"CanonicalPathQ[\"invalid\"]",
"CanonicalPathQ[CanonicalPath[{{2, 3}, {1, 2}}]]"
},
"TreePathToPath" -> {
"TreePathToPath[{{1}, {2}}]",
"TreePathToPath[{{1}, {2}}, {a, b}]",
"TreePathToPath[{{{1}, {2}}, {3}}]",
"TreePathToPath[{{1}, {{2}, {3}}}]",
"TreePathToPath[{{1}, {2}, {3}}, {a, b, c}]",
"TreePathToPath[{{1}}, {a}]",
"TreePathToPath[{{1}, {2, 3}}, {a, b, c}]",
"TreePathToPath[{{1}, {2}}, Automatic]",
"TreePathToPath[{{1}, {2}, {3}}]",
"TreePathToPath[treePath, data[\"Vertices\"]]"
},
"PathToTreePath" -> {
"PathToTreePath[{{1, 2}}]",
"PathToTreePath[{{1, 2}}, {a, b}]",
"PathToTreePath[{{1, 2}, {1, 2}}]",
"PathToTreePath[{{1, 2}, {2, 3}, {1, 3}}]",
"PathToTreePath[{{1}}]",
"PathToTreePath[{{1, 2}}, Automatic]",
"PathToTreePath[{{1, 2}, {2, 3}}, {a, b, c}]",
"PathToTreePath[path]",
"PathToTreePath[CanonicalPath[{{2, 3}, {1, 2}}]]",
"PathToTreePath[{{1, 2}, {2, 3}, {3, 4}}, Range[4]]"
},
"CanonicalPath" -> {
"CanonicalPath[{{2, 3}, {1, 2}}]",
"CanonicalPath[{{2, 3}, {1, 2}}, {a, b, c}]",
"CanonicalPath[{{1, 2}}]",
"CanonicalPath[{{1, 2}, {2, 3}, {1, 3}}]",
"CanonicalPath[{{1}}]",
"CanonicalPath[{{1, 2}}, Automatic]",
"CanonicalPath[{{1, 2}, {2, 3}}, {a, b, c}]",
"CanonicalPath[path]",
"CanonicalPath[{{3, 4}, {1, 2}, {2, 3}}]",
"CanonicalPath[{{1, 2}, {2, 3}, {3, 4}}, Range[4]]"
},
"PathIndexContractions" -> {
"indices = {{a, b}, {b, c}, {c, d}}; pathP = {{1, 2}, {1, 2}}; PathIndexContractions[pathP, indices]",
"PathIndexContractions[pathP, indices, TensorNetworkContractions[TensorNetwork[{A, B, C}, indices]]]",
"PathIndexContractions[pathP, <|\"Indices\" -> indices, \"Contractions\" -> TensorNetworkContractions[TensorNetwork[{A, B, C}, indices]]|>]",
"PathIndexContractions[path, data[\"Indices\"]]",
"PathIndexContractions[path, data[\"Indices\"], data[\"Contractions\"]]",
"PathIndexContractions[path, data]",
"PathIndexContractions[{{1, 2}}, {{i, j}, {j, k}}]",
"PathIndexContractions[{{1, 2}, {1, 2}}, {{i, j}, {j, k}, {k, i}}]",
"PathIndexContractions[{{1, 2}}, {{i}, {i}}]",
"PathIndexContractions[{{1, 2}, {2, 3}}, {{i, j}, {j, k}, {k, l}}]"
},
"MPSCanonicalForm" -> {
"MPSCanonicalForm[mps]",
"MPSCanonicalForm[mps, \"Left\"]",
"MPSCanonicalForm[mps, \"Right\"]",
"MPSCanonicalForm[mps, {\"Mixed\", 3}]",
"MPSCanonicalForm[mps, \"Left\", \"MaxBond\" -> 4]",
"MPSCanonicalForm[mps, \"Left\", \"Tolerance\" -> 1.*^-6]",
"MPSCanonicalForm[mps2, \"Left\"]",
"MPSCanonicalForm[mps2, \"Right\", \"MaxBond\" -> 5]",
"MPSCanonicalForm[mps2, {\"Mixed\", 2}, \"Tolerance\" -> 1.*^-8]",
"MPSCanonicalForm[RandomTensorNetwork[\"MPS\"[4, 2, 2]], \"Left\", \"MaxBond\" -> 3, \"Tolerance\" -> 0]"
},
"MPSCanonicalQ" -> {
"MPSCanonicalQ[MPSCanonicalForm[mps, \"Left\"], \"Left\"]",
"MPSCanonicalQ[MPSCanonicalForm[mps, \"Right\"], \"Right\"]",
"MPSCanonicalQ[MPSCanonicalForm[mps, {\"Mixed\", 3}], {\"Mixed\", 3}]",
"MPSCanonicalQ[mps, \"Left\"]",
"MPSCanonicalQ[mps, \"Right\"]",
"MPSCanonicalQ[mps2, \"Left\"]",
"MPSCanonicalQ[mps2, \"Right\"]",
"MPSCanonicalQ[mps2, {\"Mixed\", 2}]",
"MPSCanonicalQ[MPSCanonicalForm[mps2, {\"Mixed\", 2}, \"MaxBond\" -> 3], {\"Mixed\", 2}]",
"MPSCanonicalQ[MPSCanonicalForm[mps, \"Left\", \"Tolerance\" -> 1.*^-8], \"Left\"]"
},
"MPSOverlap" -> {
"MPSOverlap[mps, mps]",
"MPSOverlap[mps, mps2]",
"MPSOverlap[mps2, mps2]",
"MPSOverlap[mps, RandomTensorNetwork[\"MPS\"[5, 3, 2]]]",
"MPSOverlap[mps2, RandomTensorNetwork[\"MPS\"[5, 3, 2], \"Boundary\" -> \"Periodic\"]]",
"MPSOverlap[MPSNormalize[mps], MPSNormalize[mps]]",
"MPSOverlap[MPSCanonicalForm[mps, \"Left\"], MPSCanonicalForm[mps, \"Left\"]]",
"MPSOverlap[MPSCanonicalForm[mps, \"Right\"], MPSCanonicalForm[mps, \"Right\"]]",
"MPSOverlap[mps, MPSCanonicalForm[mps, {\"Mixed\", 3}]]",
"MPSOverlap[MPSCanonicalForm[mps2, {\"Mixed\", 2}], MPSCanonicalForm[mps2, {\"Mixed\", 2}]]"
},
"MPSNorm" -> {
"MPSNorm[mps]",
"MPSNorm[mps2]",
"MPSNorm[MPSNormalize[mps]]",
"MPSNorm[MPSCanonicalForm[mps, \"Left\"]]",
"MPSNorm[MPSCanonicalForm[mps, \"Right\"]]",
"MPSNorm[MPSCanonicalForm[mps, {\"Mixed\", 3}]]",
"MPSNorm[MPSCanonicalForm[mps2, {\"Mixed\", 2}]]",
"MPSNorm[MPSCanonicalForm[mps2, \"Right\"]]",
"MPSNorm[MPSCanonicalForm[mps2, \"Left\"]]",
"MPSNorm[RandomTensorNetwork[\"MPS\"[4, 2, 2]]]"
},
"MPSNormalize" -> {
"MPSNormalize[mps]",
"MPSNormalize[mps2]",
"MPSNormalize[MPSCanonicalForm[mps, \"Left\"]]",
"MPSNormalize[MPSCanonicalForm[mps, \"Right\"]]",
"MPSNormalize[MPSCanonicalForm[mps, {\"Mixed\", 3}]]",
"MPSNormalize[MPSCanonicalForm[mps2, {\"Mixed\", 2}]]",
"MPSNormalize[MPSCanonicalForm[mps2, \"Right\"]]",
"MPSNormalize[MPSCanonicalForm[mps2, \"Left\"]]",
"MPSNormalize[RandomTensorNetwork[\"MPS\"[4, 2, 2]]]",
"MPSNormalize[RandomTensorNetwork[\"MPS\"[4, 2, 2], \"Boundary\" -> \"Periodic\"]]"
},
"MPSEntanglementEntropy" -> {
"MPSEntanglementEntropy[mps, 2]",
"MPSEntanglementEntropy[mps, 3]",
"MPSEntanglementEntropy[mps2, 2]",
"MPSEntanglementEntropy[mps2, 3]",
"MPSEntanglementEntropy[MPSCanonicalForm[mps, \"Left\"], 2]",
"MPSEntanglementEntropy[MPSCanonicalForm[mps, \"Right\"], 2]",
"MPSEntanglementEntropy[MPSCanonicalForm[mps, {\"Mixed\", 3}], 3]",
"MPSEntanglementEntropy[MPSCanonicalForm[mps2, {\"Mixed\", 2}], 2]",
"MPSEntanglementEntropy[MPSNormalize[mps], 2]",
"MPSEntanglementEntropy[MPSNormalize[mps2], 2]"
},
"MPSSchmidtValues" -> {
"MPSSchmidtValues[mps, 2]",
"MPSSchmidtValues[mps, 3]",
"MPSSchmidtValues[mps2, 2]",
"MPSSchmidtValues[mps2, 3]",
"MPSSchmidtValues[MPSCanonicalForm[mps, \"Left\"], 2]",
"MPSSchmidtValues[MPSCanonicalForm[mps, \"Right\"], 2]",
"MPSSchmidtValues[MPSCanonicalForm[mps, {\"Mixed\", 3}], 3]",
"MPSSchmidtValues[MPSCanonicalForm[mps2, {\"Mixed\", 2}], 2]",
"MPSSchmidtValues[MPSNormalize[mps], 2]",
"MPSSchmidtValues[MPSNormalize[mps2], 2]"
},
"MPSTruncate" -> {
"MPSTruncate[mps, 4]",
"MPSTruncate[mps, 2]",
"MPSTruncate[mps, 4, \"Normalize\" -> False]",
"MPSTruncate[mps2, 4]",
"MPSTruncate[mps2, 2, \"Normalize\" -> False]",
"MPSTruncate[MPSCanonicalForm[mps, \"Left\"], 3]",
"MPSTruncate[MPSCanonicalForm[mps, \"Right\"], 3, \"Normalize\" -> False]",
"MPSTruncate[MPSCanonicalForm[mps, {\"Mixed\", 3}], 3]",
"MPSTruncate[MPSNormalize[mps], 3]",
"MPSTruncate[MPSNormalize[mps2], 3, \"Normalize\" -> False]"
},
"YoungTableau" -> {
"YoungTableau[{{1, 2}, {3}}]",
"YoungTableau[{2, 1}]",
"YoungTableau[{3}]",
"YoungTableau[{1, 1, 1}]",
"YoungTableau[{2, 2}]",
"YoungTableau[{4, 2, 1}]",
"YoungTableau[{2, 1, 1}]",
"YoungTableau[{3, 1}]",
"YoungTableau[{5}]",
"YoungTableau[{2, 2, 2}]"
},
"YoungTableauQ" -> {
"YoungTableauQ[yt1]",
"YoungTableauQ[yt2]",
"YoungTableauQ[YoungTableau[{2, 1}]]",
"YoungTableauQ[YoungTableau[{{1, 2}, {3}}]]",
"YoungTableauQ[YoungTableau[{3}]]",
"YoungTableauQ[YoungTableau[{1, 1, 1}]]",
"YoungTableauQ[YoungTableau[{2, 2}]]",
"YoungTableauQ[YoungTableau[{4, 2, 1}]]",
"YoungTableauQ[YoungTableau[{2, 2, 2}]]",
"YoungTableauQ[\"invalid\"]"
},
"TableauShape" -> {
"TableauShape[yt1]",
"TableauShape[yt2]",
"TableauShape[YoungTableau[{2, 1}]]",
"TableauShape[YoungTableau[{3}]]",
"TableauShape[YoungTableau[{1, 1, 1}]]",
"TableauShape[YoungTableau[{2, 2}]]",
"TableauShape[YoungTableau[{4, 2, 1}]]",
"TableauShape[YoungTableau[{2, 2, 2}]]",
"TableauShape[YoungTableau[{3, 1}]]",
"TableauShape[YoungTableau[{5}]]"
},
"TableauSize" -> {
"TableauSize[yt1]",
"TableauSize[yt2]",
"TableauSize[YoungTableau[{2, 1}]]",
"TableauSize[YoungTableau[{3}]]",
"TableauSize[YoungTableau[{1, 1, 1}]]",
"TableauSize[YoungTableau[{2, 2}]]",
"TableauSize[YoungTableau[{4, 2, 1}]]",
"TableauSize[YoungTableau[{2, 2, 2}]]",
"TableauSize[YoungTableau[{3, 1}]]",
"TableauSize[YoungTableau[{5}]]"
},
"HookLength" -> {
"HookLength[yt1, {1, 1}]",
"HookLength[yt1, {1, 2}]",
"HookLength[yt1, {2, 1}]",
"HookLength[yt2, {1, 1}]",
"HookLength[yt2, {2, 1}]",
"HookLength[YoungTableau[{3}], {1, 1}]",
"HookLength[YoungTableau[{1, 1, 1}], {1, 1}]",
"HookLength[YoungTableau[{2, 2}], {1, 2}]",
"HookLength[YoungTableau[{4, 2, 1}], {2, 1}]",
"HookLength[YoungTableau[{2, 2, 2}], {3, 1}]"
},
"TableauDimension" -> {
"TableauDimension[yt1]",
"TableauDimension[yt2]",
"TableauDimension[YoungTableau[{2, 1}]]",
"TableauDimension[YoungTableau[{3}]]",
"TableauDimension[YoungTableau[{1, 1, 1}]]",
"TableauDimension[YoungTableau[{2, 2}]]",
"TableauDimension[YoungTableau[{4, 2, 1}]]",
"TableauDimension[YoungTableau[{2, 2, 2}]]",
"TableauDimension[YoungTableau[{3, 1}]]",
"TableauDimension[YoungTableau[{5}]]"
},
"YoungSymmetrize" -> {
"YoungSymmetrize[t3, yt1]",
"YoungSymmetrize[t3, yt2]",
"YoungSymmetrize[RandomReal[1, {2, 2, 2}], YoungTableau[{2, 1}]]",
"YoungSymmetrize[RandomReal[1, {3, 3, 3}], YoungTableau[{3}]]",
"YoungSymmetrize[RandomReal[1, {2, 2, 2}], YoungTableau[{1, 1, 1}]]",
"YoungSymmetrize[RandomReal[1, {2, 2, 2, 2}], YoungTableau[{2, 2}]]",
"YoungSymmetrize[RandomReal[1, {3, 3, 3, 3, 3}], YoungTableau[{4, 1}]]",
"YoungSymmetrize[RandomReal[1, {2, 2, 2}], YoungTableau[{2, 1}]]",
"YoungSymmetrize[RandomReal[1, {3, 3, 3}], YoungTableau[{2, 1}]]",
"YoungSymmetrize[RandomReal[1, {4, 4, 4, 4}], YoungTableau[{2, 2}]]"
},
"YoungProject" -> {
"YoungProject[t3, yt1]",
"YoungProject[t3, yt2]",
"YoungProject[RandomReal[1, {2, 2, 2}], YoungTableau[{2, 1}]]",
"YoungProject[RandomReal[1, {3, 3, 3}], YoungTableau[{3}]]",
"YoungProject[RandomReal[1, {2, 2, 2}], YoungTableau[{1, 1, 1}]]",
"YoungProject[RandomReal[1, {2, 2, 2, 2}], YoungTableau[{2, 2}]]",
"YoungProject[RandomReal[1, {3, 3, 3, 3, 3}], YoungTableau[{4, 1}]]",
"YoungProject[RandomReal[1, {2, 2, 2}], YoungTableau[{2, 1}]]",
"YoungProject[RandomReal[1, {3, 3, 3}], YoungTableau[{2, 1}]]",
"YoungProject[RandomReal[1, {4, 4, 4, 4}], YoungTableau[{2, 2}]]"
}
|>;

cells = {
    Cell["TensorNetworks Function Examples", "Title"],
    Cell["Autogenerated examples covering all exported functions (excluding IndexArray folder). Each Input cell holds 10 runnable examples.", "Text"],
    Cell[commonSetup, "Input"]
};

Do[
    AppendTo[cells, Cell[f, "Section"]];
    AppendTo[cells, Cell[StringRiffle[examples[f], "\n"], "Input"]];
    , {f, Keys[examples]}];

nb = Notebook[cells, WindowTitle -> "TensorNetworks Examples", StyleDefinitions -> "Default.nb"];
Export["GeneratedExamples.nb", nb];
Print["Wrote GeneratedExamples.nb with ", Length[cells], " cells covering ", Length[examples], " functions."];
